Aesthetics
Dr-Nekoma/lyceum pull request #45
Opened 2024-11-04 13:44 UTC by EduardoLR10

2024-11-04 23:46 UTC, mtrsk approved these changes

2024-11-05 01:04 UTC, z-silver requested changes

2024-11-05 01:11 UTC, EduardoLR10 commented on client/src/components/button.zig
> +        }} ** config.maximumCharacters };
In theory, this allows the selectable buttons to have different fonts and sounds. Now, this is not the case, but in the future, it might?

2024-11-05 01:14 UTC, EduardoLR10 commented on client/src/client.zig
> +    music.stop(&gameState);
Let's settle on doing this when `menu.assets.deinit` function comes to live, ok?

2024-11-05 01:45 UTC, z-silver approved these changes

2024-11-05 01:53 UTC, merged